# Generated by Django 4.2.7 on 2023-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
